"""Tests of the decomposition identity and of the three laws."""
import numpy as np
import pytest
from poslayers import (periodogram_identity, landscape_share, lag_covariance,
                       isochore_law, eqtl_law, saturation_exponent, fit_contact_law,
                       simulate_genome)
from poslayers.decompose import gc_slopes, gc_correct


@pytest.fixture(scope="module")
def sim():
    return simulate_genome(n_genes=300, n_chrom=2, n_samples=120, decay_len=5.0, seed=7)


def test_identity_is_exact(sim):
    """|M(f)|^2 + S(f) equals the mean single-sample periodogram to machine precision."""
    assert periodogram_identity(sim["X"])["max_relative_error"] < 1e-8


def test_landscape_dominates(sim):
    assert 0.8 < landscape_share(sim["X"]) < 1.0


def test_lag_covariance_decays(sim):
    X = sim["X"]
    C = lag_covariance(X - X.mean(0), max_lag=40)
    assert C[0] > C[5] > C[20]


def test_isochore_law_recovers_a_simulated_bias():
    """With a known per-sample GC slope, the law predicts the induced correlation."""
    s = simulate_genome(n_genes=400, n_chrom=2, n_samples=200, decay_len=3.0,
                        gc_bias_sd=0.5, cis_sd=0.0, noise_sd=0.3, seed=3)
    X, gc = s["X"], s["gc"]
    Y = X - X.mean(0)
    var_b = float(np.var(gc_slopes(X, gc)))
    sd = Y.std(0)
    i, j = 0, 1
    pred = isochore_law(var_b, gc[i], gc[j], sd[i], sd[j])
    obs = float(np.mean(Y[:, i] * Y[:, j]) / (sd[i] * sd[j]))
    assert np.sign(pred) == np.sign(obs) or abs(obs) < 0.02
    assert abs(pred - obs) < 0.25


def test_gc_correction_removes_the_artefact():
    """With no cis layer, GC correction should leave no lag-1 correlation."""
    s = simulate_genome(n_genes=400, n_chrom=2, n_samples=200, decay_len=3.0,
                        gc_bias_sd=0.6, cis_sd=0.0, noise_sd=0.3, seed=11)
    X, gc = s["X"], s["gc"]
    Y = X - X.mean(0)
    lag1 = lambda M: float(np.mean((M[:, :-1] / (M.std(0)[:-1] + 1e-12)) *
                                   (M[:, 1:] / (M.std(0)[1:] + 1e-12))))
    assert abs(lag1(gc_correct(Y, gc))) < abs(lag1(Y))


def test_eqtl_law_sign_and_scale():
    """Opposite effects give negative coupling; the scale is 2p(1-p) b1 b2."""
    assert eqtl_law(0.3, 0.4, -0.5) < 0
    assert eqtl_law(0.3, 0.4, 0.5) > 0
    assert np.isclose(eqtl_law(0.5, 1.0, 1.0), 0.5)
    assert np.isclose(eqtl_law(0.3, 0.4, 0.5, p_same_causal=0.5),
                      0.5 * eqtl_law(0.3, 0.4, 0.5))


def test_saturation_exponent_is_one_minus_occupancy():
    """k -> 1 far from saturation, k -> 0 when saturated, k = 0.5 at c = K."""
    assert saturation_exponent(1e-3, 1.0) > 0.99
    assert saturation_exponent(1e3, 1.0) < 0.01
    assert np.isclose(saturation_exponent(1.0, 1.0), 0.5)


def test_power_law_beats_fixed_size_hub():
    """Data generated by the saturating response reject the fixed-size hub model."""
    c = np.logspace(0, 3, 20)
    r = 0.002 + 0.02 * c ** 0.5
    fit = fit_contact_law(c, r)
    assert fit["power_law"]["chi2"] < fit["hub"]["chi2"]
    assert abs(fit["power_law"]["k"] - 0.5) < 0.1
